// 10 empresas ficticias variadas para validar el pipeline (spec §12 Sprint 0).
// Cubren distintos sectores, personalidades y niveles de dificultad tipográfica.
// `recraft: true` marca los 5 casos que además generan SVG (evaluar consistencia §7.3).
// Los campos replican el questionnaire (spec §4).

export const testCases = [
  {
    company_name: 'TechFlow',
    industry: 'SaaS',
    description: 'Workflow automation platform for engineering teams.',
    personality: ['Modern', 'Technical'],
    audience: 'Developers',
    feeling: ['Speed', 'Trust'],
    color_preference: 'Cool',
    recraft: true,
  },
  {
    company_name: 'Verdant',
    industry: 'Food & Beverage',
    description: 'Farm-to-table restaurant sourcing local organic produce.',
    personality: ['Elegant', 'Friendly'],
    audience: 'Consumers',
    feeling: ['Trust', 'Premium'],
    color_preference: 'Earth',
    recraft: true,
  },
  {
    company_name: 'Aurelia',
    industry: 'Fashion & Luxury',
    description: 'Handcrafted fine jewelry for a discerning clientele.',
    personality: ['Luxury', 'Minimal'],
    audience: 'Consumers',
    feeling: ['Premium', 'Simplicity'],
    color_preference: 'Monochrome',
    recraft: true,
  },
  {
    company_name: 'Pixel & Pop',
    industry: 'Entertainment',
    description: 'Indie game studio making colorful mobile puzzle games.',
    personality: ['Playful', 'Bold'],
    audience: 'Consumers',
    feeling: ['Fun', 'Innovation'],
    color_preference: 'Bold',
    recraft: true,
  },
  {
    company_name: 'Meridian Capital',
    industry: 'Finance',
    description: 'Boutique advisory firm for early-stage venture funding.',
    personality: ['Elegant', 'Technical'],
    audience: 'Enterprise',
    feeling: ['Trust', 'Premium'],
    color_preference: 'Cool',
    recraft: true,
  },
  {
    company_name: 'Nимbus', // nombre con carácter no-ASCII a propósito: caso difícil
    industry: 'SaaS',
    description: 'Cloud storage for creative teams. Note: name is stylized "Nimbus".',
    personality: ['Modern', 'Minimal'],
    audience: 'Creators',
    feeling: ['Simplicity', 'Innovation'],
    color_preference: 'Let AI decide',
    recraft: false,
  },
  {
    company_name: 'Ironside Fitness',
    industry: 'Health & Wellness',
    description: 'Strength-training gym and coaching for serious lifters.',
    personality: ['Bold', 'Technical'],
    audience: 'Consumers',
    feeling: ['Trust', 'Speed'],
    color_preference: 'Monochrome',
    recraft: false,
  },
  {
    company_name: 'Bloom Pediatrics',
    industry: 'Healthcare',
    description: 'Friendly neighborhood pediatric clinic for young families.',
    personality: ['Friendly', 'Modern'],
    audience: 'Local business',
    feeling: ['Trust', 'Simplicity'],
    color_preference: 'Warm',
    recraft: false,
  },
  {
    company_name: 'Strata Analytics',
    industry: 'SaaS',
    description: 'Data warehouse and BI dashboards for mid-market companies.',
    personality: ['Technical', 'Minimal'],
    audience: 'Enterprise',
    feeling: ['Trust', 'Innovation'],
    color_preference: 'Cool',
    recraft: false,
  },
  {
    company_name: 'The Copper Kettle',
    industry: 'Food & Beverage',
    description: 'Cozy artisan coffee roastery and neighborhood café.',
    personality: ['Friendly', 'Elegant'],
    audience: 'Local business',
    feeling: ['Premium', 'Simplicity'],
    color_preference: 'Earth',
    recraft: false,
  },
]
